name: Bug Report
description: Report a bug or crash
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: dropdown
    id: build-flavor
    attributes:
      label: Build Flavor
      description: Which version of VoidStream are you using?
      options:
        - GitHub (sideloaded)
        - Google Play
        - Amazon Appstore
        - Built from source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of VoidStream are you running?
      placeholder: "e.g., 2.0.1"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: "e.g., Fire TV Stick 4K, Shield TV Pro, Chromecast with Google TV"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android/Fire OS Version
      description: What OS version is your device running?
      placeholder: "e.g., Android 13, Fire OS 7"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: If applicable, add crash logs or screenshots to help explain your problem.
      placeholder: Paste crash logs or attach screenshots here
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of VoidStream
          required: false
