name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this? Describe the feature you'd like to see.
      placeholder: I would like VoidStream to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: plugin
    attributes:
      label: Should this be a plugin?
      description: VoidStream supports separate plugin modules. Would this feature work better as an optional plugin?
      options:
        - "No, this should be in the core app"
        - "Yes, this could be a plugin"
        - "Not sure"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: For example, here's how another app does it...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests and this is not a duplicate
          required: true
